# Generated by Django 5.1.6 on 2025-10-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profiles', '0005_alter_schedule_options_alter_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='description_en',
            field=models.TextField(blank=True, help_text='Describe your store and products (English)', null=True, verbose_name='Descripción (English)'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='slogan_en',
            field=models.CharField(blank=True, help_text='English version of your store slogan', max_length=200, null=True, verbose_name='Slogan (English)'),
        ),
    ]
