version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev
      - DJANGO_SETTINGS_MODULE=comercia.settings
    volumes:
      - .:/app
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

