# Generated by Django 5.1.6 on 2025-09-03 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('post_id', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('matched_categories', models.CharField(blank=True, help_text='Categorias detectadas', max_length=255)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['platform', 'post_id'], name='social_inge_platfor_e668ab_idx'), models.Index(fields=['published_at'], name='social_inge_publish_04d92b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X/Twitter'), ('telegram', 'Telegram')], max_length=20)),
                ('handle', models.CharField(help_text='@usuario, canal, chat o query API', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'handle'], name='social_inge_platfor_b43fce_idx')],
            },
        ),
    ]
