# Generated by Django 5.1.6 on 2025-09-08 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_chatquery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de publicación"
            ),
        ),
    ]
