# Generated by Django 5.1.6 on 2025-10-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, help_text='Describe your product in English', null=True, verbose_name='Descripción (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, help_text='Product name in English', max_length=255, null=True, verbose_name='Nombre (English)'),
        ),
    ]
